### ISSUE TITLE
RK3399 TRM

### ISSUE THREAD

**Issue by Depthkernelcore** [CaptainIRS/rk3399-svd#2]
Hello，My RK3399 TRM has not ISP registers description. Can you send me TRM of this repository using? My email depthkernel@gmail.com,Thank you!

**Comment by CaptainIRS** [comment]
After a few weeks of digging I realised that few chapters are missing in version 1.3 and 1.4 of the TRM (which is available in https://www.rockchip.fr/) which are actually found in version 1.1 and 1.2, which can be found here: https://web.archive.org/web/20211021044212/https://www.netbsd.org/~mrg/rk3399/ (The original link seems to be dead)

Specifically the following chapters are missing:
* Crypto - v1.1 part 3 chapter 10
* DDR Converser of Frequency (DCF) - v1.2 part 1 chapter 19
* DP Controller - v1.1 part 3 chapter 8
* HDCP22 Controller - v1.1 part 3 chapter 7
* Image Enhancement Processor(IEP) - v1.1 part 3 chapter 4
* Image Signal Processing (ISP) - v1.1 part 3 chapter 6
* MIPI DSI HOST Controller - v1.1 part 3 chapter 9
* Multi-format Video Decoder And Encoder - v1.1 part 3 chapter 5
* Raster Graphic Acceleration (RGA) - v1.1 part 3 chapter 2
* Type-C Power Delivery (PD) - v1.1 part 2 chapter 18
* Video Output Processor (VOP) - v1.1 part 3 chapter 3

I'm not sure if the information in these chapters are up-to-date and reflect the specifications of recently manufactured chips though.

I'll add this information to the README shortly.

**Comment by Depthkernelcore** [comment]
Thanks,but this link (https://web.archive.org/web/20211021044212/https://www.netbsd.org/~mrg/rk3399/ ) I can not access, could you push these pdf to GitHub? Thank you very much!

**Comment by CaptainIRS** [comment]
I've uploaded these files to the repo under the [trms](https://github.com/CaptainIRS/rk3399-svd/tree/main/trms) folder and added a note to the README as well. Hope you're able to access these files.

**Comment by Depthkernelcore** [comment]
Thanks ,I can download these files.
